# Generated by Django 4.0.5 on 2022-06-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=70, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo')),
                ('comentario', models.CharField(max_length=500, verbose_name='Comentario')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
