# Generated by Django 4.0.5 on 2022-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=70, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo')),
                ('password', models.CharField(max_length=8, verbose_name='password')),
            ],
        ),
    ]
